import * as React from 'react';
import { IDropdownOption } from 'office-ui-fabric-react';
import { IOdManagmentProps } from '../interfaces/IOdManagmentProps';
export default class NewODForm extends React.Component<IOdManagmentProps> {
    state: {
        setSPCRUD: any[];
        Title: string;
        EmployeeItemID: number;
        EmployeeName: string;
        EmployeeCode: string;
        Designation: string;
        FromDate: any;
        Todate: any;
        Status: string;
        SubGroup: string;
        OfficeLocation: string;
        ApproverNameId: string;
        ApproverName: string;
        ID: number;
        showDashboard: boolean;
        ODdays: number;
        Remark: string;
        Category: string;
        UserName: string;
        Approver: string;
        StartDay: string;
        HalfType: string;
        ToDate_Halftype: string;
        LastDay: string;
        categoryOptions: any[];
        startDayOption: any[];
        halfTypeOption: any[];
        Submitted: boolean;
        myRequests: any[];
    };
    constructor(props: IOdManagmentProps);
    componentDidMount(): void;
    getAllChoices: () => void;
    getEmployeeData: () => Promise<void>;
    private _formatDate;
    private _onSelectFromDate;
    private _onSelectTodate;
    private _log;
    changeCategory: (item: IDropdownOption) => void;
    changeStartDay: (item: IDropdownOption) => void;
    changeEndDay: (item: IDropdownOption) => void;
    changeEndDayType: (item: IDropdownOption) => void;
    changeFromDayType: (item: IDropdownOption) => void;
    private handleInputChange;
    private ODdaysCalculation;
    validate: () => Promise<boolean>;
    addRequest: () => Promise<boolean>;
    validateOD: () => Promise<boolean>;
    render(): React.ReactElement<IOdManagmentProps>;
}
