export interface IODRequest {
    ID: number,
    EmployeeName: string,
    ODdays: 0,
    Remark: string,
    Category: string,
    UserName: string,
    Approver: string,
    StartDay: string,
    HalfType: string,
    ToDate_Halftype: string,
    LastDay: string,
    EmployeeCode: string,
    Designation: string,
    FromDate: null,
    Todate: null,
    Status: string,
    ApproverNameId: string,
    ApproverName: string,
}